In [1]:
import torch

In [4]:
### Task 1

In [17]:
A = torch.Tensor([[1, -3], [8, 0]])
B = torch.Tensor([[-1, 1], [0, 4]])

X = torch.linalg.solve(2 * torch.eye(2), A - 3 * B)

print("Solution:")
print(X)

Solution:
tensor([[ 2., -3.],
        [ 4., -6.]])


In [10]:
### Task 2

In [20]:
A = torch.Tensor([[3, 2, 1], [2, 3, 1], [2, 1, 3]])

B = torch.Tensor([[3], [1], [4]])

C = torch.Tensor([[2], [-2], [0]])

X = torch.linalg.solve(A, B + C)

print("Solution:")
print(X)

Solution:
tensor([[ 3.4167],
        [-2.5833],
        [-0.0833]])


In [21]:
### Task3

In [22]:
A = torch.Tensor([[9, 7, 6], [1, 1, 2], [1, 1, 1]])

B = torch.Tensor([[2, 0, 2], [18, 12, 9], [24, 14, 11]])

X = torch.linalg.solve(A, B, left=False)

print("Solution:")
print(X)

Solution:
tensor([[ 1.0000e+00,  3.0000e+00, -1.0000e+01],
        [ 3.0000e+00, -2.5332e-07, -9.0000e+00],
        [ 5.0000e+00,  2.0000e+00, -2.3000e+01]])


In [13]:
### Task 4

In [24]:
A = torch.Tensor([[2, 1, 3], [-1, 4, 2], [1, 2, -2]])

B = torch.Tensor([[3, 1, 2], [4, -1, 3]])

C = torch.Tensor([[0, -1, 2], [-1, 2, 0]])

X = torch.linalg.solve(A, 5 * C - 2 * B, left=False)

print("Solution:")
print(X)

tensor([[-0.8571,  0.4048, -3.8810],
        [-4.5714,  4.0476,  0.1905]])


In [26]:
### Task 5

In [31]:
A = torch.Tensor([[3, 1, -1], [-1, 1, 2], [1, 3, 1]])

B = torch.Tensor([[2, -3], [1, 1], [-2, -3]])

C = torch.Tensor([[2, -8], [3, 5], [-8, -5]])

D = torch.zeros([3, 2])

X = torch.linalg.solve(A, D + 2 * C - 5 * B)

print("Solution:")
print(X)

Solution:
tensor([[-1.0000e+00, -1.2914e-07],
        [-2.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  2.0000e+00]])
