# NumPy vs Iterative Constructions Exercises
This notebook contains:
1. Vectorized (NumPy) and iterative (pure Python) solutions for selected exercises, with timing comparisons.
2. Solving a system of algebraic equations using Cramer's rule, verified by matrix multiplication, inverse, and numpy.linalg.solve().
3. Computing the matrix expression $2(A+B)(2B - A)$ using both approaches, with timing and validation.

## Exercise 1
The number $n$ is entered. Print an array of size $n\times n$, in which the numbers from 1 to $n$ go diagonally, and the rest of the numbers are 0.

In [1]:
import numpy as np
import time

def ex1_numpy(n):
    arr = np.zeros((n, n), dtype=int)
    np.fill_diagonal(arr, np.arange(1, n+1))
    return arr

def ex1_iter(n):
    arr = [[0]*n for _ in range(n)]
    for i in range(n):
        arr[i][i] = i+1
    return np.array(arr)

# Timing
n = 1000
t0 = time.time(); _ = ex1_numpy(n); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex1_iter(n); t1 = time.time(); t_iter = t1 - t0
print(f"Ex1 (n={n}): numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex1 (n=1000): numpy 0.001088s, iter 0.031576s


## Exercise 6
An array is entered from the keyboard. Replace all non-zero elements with $-1$.

In [2]:
import numpy as np
import time

def ex6_numpy(arr):
    result = arr.copy()
    result[result != 0] = -1
    return result

def ex6_iter(arr):
    result = arr.copy().tolist()
    for i in range(len(result)):
        for j in range(len(result[0])):
            if result[i][j] != 0:
                result[i][j] = -1
    return np.array(result)

# Demonstration and timing
arr = np.random.randint(-5, 5, (1000, 1000))
t0 = time.time(); _ = ex6_numpy(arr); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex6_iter(arr); t1 = time.time(); t_iter = t1 - t0
print(f"Ex6: numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex6: numpy 0.003372s, iter 0.055928s


## Exercise 7
An array is entered from the keyboard. Replace all zero elements with $-1$.

In [3]:
import numpy as np
import time

def ex7_numpy(arr):
    result = arr.copy()
    result[result == 0] = -1
    return result

def ex7_iter(arr):
    result = arr.copy().tolist()
    for i in range(len(result)):
        for j in range(len(result[0])):
            if result[i][j] == 0:
                result[i][j] = -1
    return np.array(result)

# Demonstration and timing
arr = np.random.randint(0, 5, (1000, 1000))
t0 = time.time(); _ = ex7_numpy(arr); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex7_iter(arr); t1 = time.time(); t_iter = t1 - t0
print(f"Ex7: numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex7: numpy 0.002769s, iter 0.045770s


## Exercise 9
The number $n$ is entered. Create an array of values from $n$ to 0.

In [4]:
import numpy as np
import time

def ex9_numpy(n):
    return np.arange(n, -1, -1)

def ex9_iter(n):
    return np.array([i for i in range(n, -1, -1)])

# Timing
n = 1000000
t0 = time.time(); _ = ex9_numpy(n); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex9_iter(n); t1 = time.time(); t_iter = t1 - t0
print(f"Ex9 (n={n}): numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex9 (n=1000000): numpy 0.000462s, iter 0.033121s


## Exercise 10
The numbers $n$ and $m$ are given. Create an array of random values $n\times m$ and calculate the minimum, maximum, average, and standard deviation, rounded to 3 decimal places.

In [5]:
import numpy as np
import time
import random
import math

def ex10_numpy(n, m):
    arr = np.random.random((n, m))
    return np.round(np.min(arr), 3), np.round(np.max(arr), 3), np.round(np.mean(arr), 3), np.round(np.std(arr), 3)

def ex10_iter(n, m):
    total = 0.0; total2 = 0.0; count = n*m
    minimum = 1.0; maximum = 0.0
    for _ in range(n*m):
        v = random.random()
        total += v; total2 += v*v
        if v < minimum: minimum = v
        if v > maximum: maximum = v
    mean = total / count
    std = math.sqrt(total2/count - mean*mean)
    return round(minimum, 3), round(maximum, 3), round(mean, 3), round(std, 3)

# Timing
n, m = 500, 500
t0 = time.time(); _ = ex10_numpy(n, m); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex10_iter(n, m); t1 = time.time(); t_iter = t1 - t0
print(f"Ex10 ({n}x{m}): numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex10 (500x500): numpy 0.001827s, iter 0.018026s


## Exercise 11
Create an array of ones of size $n\times n$ and add a “frame” to it, starting with 0.

In [6]:
import numpy as np
import time

def ex11_numpy(n):
    arr = np.ones((n, n), dtype=int)
    arr[0, :] = 0; arr[-1, :] = 0; arr[:, 0] = 0; arr[:, -1] = 0
    return arr

def ex11_iter(n):
    arr = [[1]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if i in (0, n-1) or j in (0, n-1):
                arr[i][j] = 0
    return np.array(arr)

# Timing
n = 1000
t0 = time.time(); _ = ex11_numpy(n); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex11_iter(n); t1 = time.time(); t_iter = t1 - t0
print(f"Ex11 (n={n}): numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex11 (n=1000): numpy 0.000847s, iter 0.069324s


## Exercise 15
Fill the even columns of the matrix of size $n\times n$ with ones and the odd columns with zeros.

In [7]:
import numpy as np
import time

def ex15_numpy(n):
    arr = np.zeros((n, n), dtype=int)
    arr[:, ::2] = 1
    return arr

def ex15_iter(n):
    arr = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            arr[i][j] = 1 if j % 2 == 0 else 0
    return np.array(arr)

# Timing
n = 1000
t0 = time.time(); _ = ex15_numpy(n); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex15_iter(n); t1 = time.time(); t_iter = t1 - t0
print(f"Ex15 (n={n}): numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex15 (n=1000): numpy 0.000731s, iter 0.044639s


## Exercise 17
Fill the vector with values from 0 to $n$. Replace signs for all values less than $n/2$ and greater than $3n/4$ with opposite signs.

In [8]:
import numpy as np
import time

def ex17_numpy(n):
    arr = np.arange(n+1)
    mask = (arr < n/2) | (arr > 3*n/4)
    arr[mask] = -arr[mask]
    return arr

def ex17_iter(n):
    arr = list(range(n+1))
    for i, v in enumerate(arr):
        if v < n/2 or v > 3*n/4:
            arr[i] = -v
    return np.array(arr)

# Timing
n = 10000000
t0 = time.time(); _ = ex17_numpy(n); t1 = time.time(); t_numpy = t1 - t0
t0 = time.time(); _ = ex17_iter(n); t1 = time.time(); t_iter = t1 - t0
print(f"Ex17 (n={n}): numpy {t_numpy:.6f}s, iter {t_iter:.6f}s")

Ex17 (n=10000000): numpy 0.041199s, iter 0.827502s


## Exercise 18
Generate a vector of $n$ random numbers in the range from 0 to 99. Find the number of unique numbers in the sequence.

In [9]:
import numpy as np
import time
import random

def ex18_numpy(n):
    arr = np.random.randint(0, 100, size=n)
    return len(np.unique(arr))

def ex18_iter(n):
    arr = [random.randint(0, 99) for _ in range(n)]
    return len(set(arr))

# Timing
n = 1000000
t0 = time.time(); _ = ex18_numpy(n); t1 = time.time(); numpy_time = t1 - t0
t0 = time.time(); _ = ex18_iter(n); t1 = time.time(); iter_time = t1 - t0
print(f"Ex18 (n={n}): numpy {numpy_time:.6f}s, iter {iter_time:.6f}s")

Ex18 (n=1000000): numpy 0.023910s, iter 0.224542s


## Part 2: Solving a System of Equations
Solve using Cramer's rule and verify:
a) Matrix multiplication
b) Inverse matrix multiplication
c) `numpy.linalg.solve()`

The system is:
\[
\begin{cases}
 x_1 + x_2 + 2x_3 + 3x_4 = 1\\
 3x_1 - x_2 - x_3 - 2x_4 = -4\\
 2x_1 - 3x_2 - x_3 - x_4 = -6\\
 x_1 + 2x_2 + 3x_3 - x_4 = -4
\end{cases}
\]

In [10]:
import numpy as np

A = np.array([[1,1,2,3],[3,-1,-1,-2],[2,-3,-1,-1],[1,2,3,-1]], dtype=float)
b = np.array([1,-4,-6,-4], dtype=float)

# Cramer's rule
detA = np.linalg.det(A)
x_cramer = np.zeros(4)
for i in range(4):
    Ai = A.copy()
    Ai[:, i] = b
    x_cramer[i] = np.linalg.det(Ai) / detA

# Verification
res_mul = A.dot(x_cramer)
res_inv = np.linalg.inv(A).dot(b)
x_solve = np.linalg.solve(A, b)

print("Cramer's solution:", x_cramer)
print("Numpy solve solution:", x_solve)
print("A @ x_cramer ≈ b:", np.allclose(res_mul, b))
print("inv(A) @ b ≈ x_cramer:", np.allclose(res_inv, x_cramer))
print("cramer ≈ solve:", np.allclose(x_cramer, x_solve))

Cramer's solution: [-0.55555556  1.88888889 -2.          1.22222222]
Numpy solve solution: [-0.55555556  1.88888889 -2.          1.22222222]
A @ x_cramer ≈ b: True
inv(A) @ b ≈ x_cramer: True
cramer ≈ solve: True


## Part 3: Matrix Expression
Calculate $2(A+B)(2B - A)$ using:
a) NumPy universal functions
b) Iterative constructs

Matrices:
A = [[2, 3, -1], [4, 5, 2], [-1, 0, 7]]
B = [[-1, 0, 5], [0, 1, 3], [2, -2, 4]]

In [11]:
import numpy as np
import time

A = np.array([[2,3,-1],[4,5,2],[-1,0,7]])
B = np.array([[-1,0,5],[0,1,3],[2,-2,4]])

# Vectorized
t0 = time.time()
C_vec = 2 * (A + B).dot(2*B - A)
t1 = time.time(); t_vec = t1 - t0

# Iterative
def mat_mult(X, Y):
    return [[sum(X[i][k] * Y[k][j] for k in range(len(Y))) for j in range(len(Y))] for i in range(len(X))]

t0 = time.time()
M1 = (A + B).tolist()
M2 = (2*B - A).tolist()
prod = mat_mult(M1, M2)
C_iter = np.array([[2 * prod[i][j] for j in range(len(prod))] for i in range(len(prod))])
t1 = time.time(); t_iter = t1 - t0

print("C_vec:\n", C_vec)
print("C_iter:\n", C_iter)
print("All close?", np.allclose(C_vec, C_iter))
print(f"Times: vectorized {t_vec:.6f}s, iterative {t_iter:.6f}s")

C_vec:
 [[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]
C_iter:
 [[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]
All close? True
Times: vectorized 0.000048s, iterative 0.000088s


## Conclusions
- In all timed exercises, the NumPy vectorized implementations were significantly faster than the pure Python iterative versions, especially for large data sizes.
- Cramer's rule yields the same solution as `numpy.linalg.solve`, and matrix multiplication and inverse-based methods verify correctness.
- The matrix expression computed iteratively matches the vectorized result, but vectorized computation is far more efficient.